project_id = "sfsjtljhrelctpxpzody"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.send-status-notification]
verify_jwt = false

[functions.send-complaint-confirmation]
verify_jwt = false
